service: exchange
frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 3

  apiGateway:
    apiKeys:
      - exchangeTextKey
    usagePlan:
      throttle:
        burstLimit: 5
        rateLimit: 3

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:PutItem
        - dynamodb:GetItem
      Resource: !GetAtt RequestsTable.Arn
    - Effect: Allow
      Action:
        - secretsmanager:GetSecretValue
      Resource: !Ref APISecret

  environment:
    REQUESTSTABLE: !Ref RequestsTable
    APIKEY: !Ref APISecret

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  Exchange:
    handler: bin/exchange
    events:
      - http:
          path: /{base}/{target}/{amount}
          method: get
  ExchangeEvent:
    handler: bin/exchangeevent
    events:
      - http:
          path: /event/{id}
          method: get

resources:
  Resources:
    RequestsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-${self:provider.stage}-requests
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
    APISecret:
      Type: AWS::SecretsManager::Secret
      Properties:
        Name: ${self:service}-${self:provider.stage}-secret
        Description: FOREX service API key
          